runtime: nodejs12
service: frontend-react
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /login
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
  - url: /login
    static_dir: build
